import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Sora:wght@700&display=swap');
      </style>
      <body
        className=""
      >
        {children}
      </body>
    </html>
  );
}
